os: linux
dist: xenial
sudo: required
language: generic
notifications:
  email:
    on_success: never
    on_failure: never
script:
  - export ORG="`echo \"$TRAVIS_COMMIT_MESSAGE\" | grep -Eo \"ORG=.*\" | awk -F'=' '{print $2}'`"
  - echo $ORG
  - export BOX="`echo \"$TRAVIS_COMMIT_MESSAGE\" | grep -Eo \"BOX=.*\" | awk -F'=' '{print $2}'`"
  - echo $BOX
  - export PROVIDER="`echo \"$TRAVIS_COMMIT_MESSAGE\" | grep -Eo \"PROVIDER=.*\" | awk -F'=' '{print $2}'`"
  - echo $PROVIDER
  - export VERSION="`echo \"$TRAVIS_COMMIT_MESSAGE\" | grep -Eo \"ORG=.*\" | awk -F'=' '{print $2}'`"
  - echo $VERSION
  - docker pull ladar/scanman:latest
  - docker run --cap-add=CAP_MKNOD --privileged -ti ladar/scanman:latest bash -c "/root/scan.sh ${ORG} ${BOX} ${PROVIDER} ${VERSION}"
  - echo "${ORG} ${BOX} ${PROVIDER} ${VERSION} finished."
  - echo $ORG $BOX $PROVIDER $VERSION finished.
  - env
  - docker run --cap-add=CAP_MKNOD --privileged -ti ladar/scanman:latest bash -c "/root/scan.sh generic centos7 vmware 1.8.50"
  - docker run --cap-add=CAP_MKNOD --privileged -ti ladar/scanman:latest bash -c "bash -x /root/scan.sh generic centos7 vmware 1.8.50"

  
