os: linux
dist: xenial
sudo: required
language: generic
notifications:
  email:
    on_success: never
    on_failure: never
script:
  - source .params.sh
  - docker run --cap-add=CAP_MKNOD --privileged -ti ladar/scanman:latest bash -c "bash /root/scan.sh $ORG $BOX $PROVIDER $VERSION" | tee "$ORG-$BOX-$PROVIDER-$VERSIOtee "$ORG-$BOX-$PROVIDER-$VERSION resultsN.txt"
  - echo $ORG $BOX $PROVIDER $VERSION finished.
  - git add "$ORG-$BOX-$PROVIDER-$VERSION.txt" && git rm .travis.yml
  - git commit -m "tee "$ORG-$BOX-$PROVIDER-$VERSION results" &&git push 
