os: linux
dist: xenial
sudo: required
language: generic
notifications:
  email:
    on_success: never
    on_failure: never
script:
  - export ORG=`echo "$TRAVIS_COMMIT_MESSAGE" | grep ORG | awk -F'=' '{print $2}'`
  - echo $ORG
  - export BOX=`echo "$TRAVIS_COMMIT_MESSAGE" | grep BOX | awk -F'=' '{print $2}'`
  - echo $BOX
  - export PROVIDER=`echo "$TRAVIS_COMMIT_MESSAGE" | grep PROVIDER | awk -F'=' '{print $2}'`
  - echo $PROVIDER
  - export VERSION=`echo "$TRAVIS_COMMIT_MESSAGE" | grep VERSION | awk -F'=' '{print $2}'`
  - echo $VERSION
  - (for ((i = 0; i < 60; ++i)); do sleep 60 ; printf "%s (%s )\n" "`date`" "`uptime`" ; done) & LOOP_PID=$! ; disown
  - docker pull ladar/scanman:latest
  - docker run --cap-add=CAP_MKNOD --privileged -ti ladar/scanman:latest /root/scan.sh $ORG $BOX $PROVIDER $VERSION
  - echo $ORG $BOX $PROVIDER $VERSION finished.
  - kill $LOOP_PID
  
